name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up ARM GCC toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: 'latest'  # Or specify a version like '10.3-2021.10'
    
    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build -- -j4
    
    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/*.hex
          build/*.bin
          Debug/*.hex
          Debug/*.bin
          Release/*.hex
          Release/*.bin
  
  static-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck
    
    - name: Run Cppcheck
      run: |
        mkdir -p build
        cd build
        cmake ..
        make cppcheck
    
    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: static-analysis
        path: build/cppcheck-result.xml
