name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Ninja Build
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Configure CMake
      run: cmake -G "Ninja" -B build -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/arm-gcc-toolchain.cmake" "${{ github.workspace }}"

    - name: Build Project
      run: cmake --build build -- -j4
    
    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/*.hex
          build/*.bin
          Debug/*.hex
          Debug/*.bin
          Release/*.hex
          Release/*.bin
  
  static-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck
    
    - name: Run Cppcheck
      run: |
        mkdir -p build
        cd build
        cmake ..
        make cppcheck
    
    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: static-analysis
        path: build/cppcheck-result.xml
