name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: default
            features: ''
          - name: debounce-polling
            features: '--features debounce,polling'
          - name: debounce-interrupt
            features: '--features debounce,interrupt'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Cargo fmt
        run: cargo fmt --all --check
      - name: Cargo clippy
        run: cargo clippy ${{ matrix.features }} -- -D warnings
      - name: Cargo test
        run: cargo test ${{ matrix.features }}
      - name: Coverage
        run: cargo tarpaulin ${{ matrix.features }} --out Xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./tarpaulin-report.xml
