name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: thumbv7em-none-eabihf
      - name: Cargo check (core)
        run: cargo check -p keyboard-core
      - name: Cargo check (firmware)
        run: cargo check -p firmware --target thumbv7em-none-eabihf
      - name: Cargo check (simulator)
        run: cargo check -p simulator
      - name: Cargo check (bootloader)
        run: cargo check -p bootloader --target thumbv7em-none-eabihf
