name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '10.3-2021.10'
    
    - name: Build Project
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-none-eabi-gcc.cmake
        make
    
    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/*.hex
          build/*.bin
  
  static-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck
    
    - name: Run Cppcheck
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-none-eabi-gcc.cmake
        make cppcheck
    
    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: static-analysis
        path: build/cppcheck-result.xml
